language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew build

after_success:
 - mkdir codedeploy
 - zip -r TestJavaProject-${TRAVIS_JOB_NUMBER}.zip build/libs/ROOT.war appspec.yml
 - ls -al
 - mv TestJavaProject-${TRAVIS_JOB_NUMBER}.zip codedeploy/
 - ls -al
 - pwd
 - cd codedeploy
 - ls -al
 - pwd


before_deploy:
 - cd ..


deploy:
 - provider: s3
   access_key_id: $ACCESS_KEY_ID
   secret_access_key: $SECRET_ACCESS_KEY
   local_dir: codedeploy
   bucket: code-deploy.csye6225-fall2017-patelshu.me
   region: us-east-1
   skip_cleanup: true
   all_branches: true

notifications:
  email:
    recipients:

    - patel.shu@husky.neu.edu
    - sawant.ap@husky.neu.edu
    - chabhadia.r@husky.neu.edu