language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew build

after_success:
 - mkdir codedeploy
 - zip -r SimpleTestJAVA-${TRAVIS_JOB_NUMBER}.zip build/lib/ROOT.war appspec.yml
 - ls -al
 - mv SimpleTestJAVA-${TRAVIS_JOB_NUMBER}.zip codedeploy/
 - ls -al
 - pwd
 - cd codedeploy
 - ls -al
 - pwd


before_deploy:
 - cd ..


deploy:
 - provider: s3
   access_key_id: AKIAILJNNSYHRZPOQLNA
   secret_access_key:
    secure: eoEFbTSt4WAnvMTcehrLk1m6adXXrRydgy3T9YxVCYRqDJX4lOCm17sPXc0uPxsaFL7UxOvTUz2i2kqKP1D6IluHoeVei5RIK0dOk4DLNC+rpjcnrjjNfnVWi2wZfvRgP160N5d8vVz1f8rGBDZ86/OZkxTqWGGdhsGZIE27bRkeaD71yr9hZQFCvS272X5sxbkGtnoCth8BEC3VZNVxfacgLEhmuBToEMFFzlUxNOjkfvstZOXSDPGu5OKMtjDP776p0YjW26fYtXMxm2yOGkT/LKJ31pxkXx68YgjrP63t94B8DXMc/agCU8q0FVY779NZJIaibyEdCCQEDB/zO08Qfn+gWjRIpyfkFk9N087CFpXZ2YdupvfGAYKLGh4MfcVvcWQUBg/kbyU2u6ihMZifXV8EW7DAKig3yHvf39SHiLWfb4YnUEBheCZKE3kbM1QnvFC28spEdEsg83wk27ZV1HUYSIVylzSubj+SoRZXIp4wRsPwuhO7qxloPcbzO4u+77UE5pknqYy1hEBTkHRz5kfWJAmq+VkvnzGdbkvJ7phsZliwvAMQLfuZ91jEiUW7wOURcPie/xAKszMN3iY0HzdPj47Mrf0Hq1E/hMMFP1elByqYNBMeXSI6HAsyitU3DW9z8VI86WsmRIDUtb6CsjyFgkBRH0rIDc3sNY0=
   loacl_dir: codedeploy
   bucket: code-deploy.csye6225-fall2017-chabhadiar.me
   region: us-east-1
   skip_cleanup: true
   on :
    all_branches: true
 - provider: codedeploy
   access_key_id: AKIAILJNNSYHRZPOQLNA
   secret_access_key:
    secure: eoEFbTSt4WAnvMTcehrLk1m6adXXrRydgy3T9YxVCYRqDJX4lOCm17sPXc0uPxsaFL7UxOvTUz2i2kqKP1D6IluHoeVei5RIK0dOk4DLNC+rpjcnrjjNfnVWi2wZfvRgP160N5d8vVz1f8rGBDZ86/OZkxTqWGGdhsGZIE27bRkeaD71yr9hZQFCvS272X5sxbkGtnoCth8BEC3VZNVxfacgLEhmuBToEMFFzlUxNOjkfvstZOXSDPGu5OKMtjDP776p0YjW26fYtXMxm2yOGkT/LKJ31pxkXx68YgjrP63t94B8DXMc/agCU8q0FVY779NZJIaibyEdCCQEDB/zO08Qfn+gWjRIpyfkFk9N087CFpXZ2YdupvfGAYKLGh4MfcVvcWQUBg/kbyU2u6ihMZifXV8EW7DAKig3yHvf39SHiLWfb4YnUEBheCZKE3kbM1QnvFC28spEdEsg83wk27ZV1HUYSIVylzSubj+SoRZXIp4wRsPwuhO7qxloPcbzO4u+77UE5pknqYy1hEBTkHRz5kfWJAmq+VkvnzGdbkvJ7phsZliwvAMQLfuZ91jEiUW7wOURcPie/xAKszMN3iY0HzdPj47Mrf0Hq1E/hMMFP1elByqYNBMeXSI6HAsyitU3DW9z8VI86WsmRIDUtb6CsjyFgkBRH0rIDc3sNY0=
   bucket: code-deploy.csye6225-fall2017-chabhadiar.me
   key: SimpleTestJAVA-${TRAVIS_JOB_NUMBER}.zip
   bundle_type: zip
   application: SimpleTestJAVA
   deployment_group: CSYE6225
   region: us-east-1
   wait-until-deployed: true



notifications:
  email:
    recipients:

    - patel.shu@husky.neu.edu
    - sawant.ap@husky.neu.edu
    - chabhadia.r@husky.neu.edu
