language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew build

after_success:
 - mkdir codedeploy
 - zip -r TestJavaProject-${TRAVIS_JOB_NUMBER}.zip build/lib/ROOT.war appspec.yml
 - ls -al
 - mv TestJavaProject-${TRAVIS_JOB_NUMBER}.zip codedeploy/
 - ls -al
 - pwd
 - cd codedeploy
 - ls -al
 - pwd


before_deploy:
 - cd ..




deploy:
 - provider: s3
   access_key_id: AKIAJHVBBILTLANLCNVQ
   secret_access_key:
    secure: nn8l1KQ9MX8tFcTMNGXBqshnYIJO/l2G3KBzhGSHZN2GzPW+oini/zb5mMJZn0tCrYU766TbADR+56Nr6g6MjYoKErz1hqX7JC0X0cecRTrnm53rH0+lROPXqh8zKChpKLHATDFeZaY4tV7onYYgSimmRiy6xTOGeZDd6LHnk2/HsSe/4RNOvGhToFz1Fj2R5IpRNW0Xi9PvlpPBRB8DRRvwl1rYR6Du8xnxIBRQRvLJbvkhA+8kCq9JLoTgZbiJ7SzKwdJHJV9NwliRN4lCjxa+myBQq/SptkMJA0n8w+urWe2dTMfPI8DkraVMbXrgu+Lq8ANdpvNJAUZMQBxjloBaJ7PVH+K/6n5QDQt3NdUheWehZoC3i4XexVu1jr4mD18Y33E96IcYXlFhIGnSlY7d70qruaCo1k5eMeNuTwzDttn+Y6/HgAXeOi9CDaZMC7r+I8+Nms4Hff2P5d3PDtyQS9e5BqpCp6xmcx4faS4bOzRkV60SDqdred7hrO530WI7FkPxfQi7YbRv8A5A4sTt1ehC8wqoyZYaTSCAFseSjo/a5GcjbujTKiURIutWwNluL7Tbh5H7HQoMXPsA22lilonEj1J/gRFeUXLwnawipb7jLIUOrc0fWPA5YsZxSGSv5f8uFlURXw9+qWj/N0CuZkGC69all/bzdFceWak=
   loacl_dir: codedeploy
   bucket: code-deploy.csye6225-fall2017-patelshu.me
   region: us-east-1
   skip_cleanup: true
   all_branches: true

notifications:
  email:
    recipients:

    - patel.shu@husky.neu.edu
    - sawant.ap@husky.neu.edu
    - chabhadia.r@husky.neu.edu


