language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew build

after_success:
 - mkdir codedeploy
 - zip -r TestJavaProject-${TRAVIS_JOB_NUMBER}.zip build/lib/ROOT.war appspec.yml
 - ls -al
 - mv TestJavaProject-${TRAVIS_JOB_NUMBER}.zip codedeploy/
 - ls -al
 - pwd
 - cd codedeploy
 - ls -al
 - pwd


before_deploy:
 - cd ..


deploy:
 - provider: s3
   access_key_id: AKIAJHVBBILTLANLCNVQ
   secret_access_key:
    secure: uAt8ooWfXG1yKaAV45ZANLuq2oyF5jwmIF/fdZ0rEBZUtr1qq5xoEnbHVJk0G6Nvvg6fXQCcRn+UkgKP2u3LGTk6aqIHR7L5F/9pZ+gxnp7rT8n/V4g2qcCPYicat2dORKcHyDA/RVf8B+8fXK8bz5wvV9YgcGf0AZzMFNM2GN3/xlXHuxNARgKHJG7n31/kEC9hadytulYeND4wzGA2HEhKa0HfeD8ZybCD0d/v8bpyYg7kC6mjs1w/5OWBt2Ttf1ubqIqcLq/T4KiCut6UNSYhLkFTk+M7WYOEB0CTdk4ZwmwB236o0sFCkBsjxSH7z0+d/hF2/Nu1FYCC64O47uZH6viUxjzPpCAAuQZbf1PcFPDIp2bsovai1jzM0TBdObS9eCjp+TWqbFMF233eMzsS8dsGe8+4N5i3bahK9pBy7Ad1IQo+eo9vWHwsgwLsXgqaGCzb5tj9wBcG/oEYqGA4T4yIJsJtSRcBdp6xEdlPMqyLe8l4j9ZaWp/1t4UXUSJOBWpzqPR0TAIywhH3fcEctx6PdY+pFjw2Iym94yQfDmNDTu8LxNfPbszI79I9Zqi2FiH09j8fKnZevunrX23k3sFdn4AJFGGFg2Oa96rIZf8hOIxUo6BFuZdlN/MeaIOVCCr7DvbTuYCehSkF1G7E9u76pDfm/h/irOMgXHU=
   loacl_dir: codedeploy
   bucket: code-deploy.csye6225-fall2017-patelshu.me
   region: us-east-1
   skip_cleanup: true
   all_branches: true

notifications:
  email:
    recipients:

    - patel.shu@husky.neu.edu
    - sawant.ap@husky.neu.edu
    - chabhadia.r@husky.neu.edu


