language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew build

after_success:
 - mkdir codedeploy
 - zip -r TestJavaProject-${TRAVIS_JOB_NUMBER}.zip build/lib/ROOT.war appspec.yml
 - ls -al
 - mv TestJavaProject-${TRAVIS_JOB_NUMBER}.zip codedeploy/
 - ls -al
 - pwd
 - cd codedeploy
 - ls -al
 - pwd


before_deploy:
 - cd ..


deploy:
 - provider: s3
   access_key_id: AKIAJHVBBILTLANLCNVQ
   secret_access_key:
    secure: aYogi949d9h7O8IsQUcZwMMMcSh+Nj5UNEu9LnuVQOEkNDSI3bp60jUiBMjlkpxIYbqVuJKkm7DLcdyPai8JRhnAF9auS7T+zKpv6Y2cVexLF0lZOn4l95PFkbzu9yFRRltFmWdWiHykOEI40HJaGBU/VgFcHB+pTuPcm9FL4A9IyVngXA0h2/MuvSKk7kgpA1h34B6T4PuTLA0sYrg8NnY0phfUjqj0LRiAPKYsk10JkPtweIGqOyoJcc7tPP7l7S7lbqQ/2qmMq5buRv/xbUsDDjMgtObImeltnapsf/8o0riev2m+i342j4fTBgS6nWNP5kCPgAjvBV36jhsWBWFkC7l+lwQ9cti/52PiCbmqZD4yCfeUkpNM+8fq+vi1q+w+kdNfhShMjdFEem05QsiUJY+B7TzODWINnUGETHgiGu6dKvgFJ9EO4Wd0lmKF8iQOqHVtR0Pu7hR6N0DKBKFbrtd5n5b4z3YA+qgcM4nr+TFkP9vFokaIABosM+6uQZUplM9dyhARsmVpaygoDspXADCczkLWzwct55smeUC22AhIe6sFw6hcfxWqEhJ6w6AF63pJFfJDd2YJFLqH8XVr9v1d7ICRl1cVNF81Lmc6yqpr9A+UJZid1kwh0zpMaGHqzK/Nlov/R5ziMCiGWJmEvoTI8XB3RNNDgRqVNig=
   loacl_dir: codedeploy
   bucket: code-deploy.csye6225-fall2017-patelshu.me
   region: us-east-1
   skip_cleanup: true
   all_branches: true

notifications:
  email:
    recipients:

    - patel.shu@husky.neu.edu
    - sawant.ap@husky.neu.edu
    - chabhadia.r@husky.neu.edu


