language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew build

after_sucess:
- mkdir codedeploy
- zip -r csye6225-${TRAVIS_JOB_NUMBER}.zip build/libs/root.war appspec.yml
- ls -al
- mv csye6225-${TRAVIS_JOB_NUMBER}.zip codedeploy/
- ls -al
- pwd
- cd codedeploy
- ls -al
- pwd

before-deploy:
- cd ..

deploy:
- provider: s3
  access_key_id: AKIAJOL6HUEB7XIADEUA
  secret_access_key:
   secure: kIUjCP4nJ4nvp1WlsExaUz9DDqYFWKLITEJS3HxKMmOhmUD+xc1o6/8O8RxMhmbuMg+it3hb4pf1LC2voyomRJKrJc4LL3nr9RfTLjVJQYR6u8bEu2ejU0oC1oV3GeGxwKoRwcRusVbTIEYrnyWyizh21U8WdZLQgzvbsDP5N1FMuB+/BdzujGAkqaoNiEt8K7hQDWxwvMi5JwgXyCHFhlvVS8XtVCPOI+Ddkt38cKdTLaMz5L3dFqPzmsfXm/gyCa3DGxMkymlMITxJyPevnzPRLFK+KV/GIy/+ifUbBxM54pnW4DjkV+LaF9ljQXci9YAtfttCgEwjictSKxwhNvzzO0VXuoZ57NICZFfh8GMxHGT2V/Jmo/hvre9q0ZWbPyZZqFcMnmSvuvAeiXFr1cCP/rQsDr0gR1t3es88nCtbKDHRT0S1An7aB2+zTavchH19lfBBa/M+yPR6hWujCyyNfKek5uPTo1OzvNjFv7muU5V8h8O234E+VVr9SVJp7LBEE0aDpzea6y6DtnnlXptQ/k+nDg88X4n42ooobonLWZQVM8Ujv+f9ulcnhjXQ/mJW4e0N5ueC8sVgwbnl+ZiS1PIK4Cq/cI6F98tfeZQM9aTf9s2YgBJlxjXRe843o1Ehq5pBi+OKSWgHzgfuuRUqS8XlBJvZ91lnMQgH/Lw=
  local_dir: codedeploy
  bucket: code-deploy.csye6225.com
  region: us-east-1
  skip_cleanup: true
  all_branches: true

notifications:
  email:
    recipients:
    - patel.shu@husky.neu.edu
    - sawant.ap@husky.neu.edu
    - chabhadia.r@husky.neu.edu


