language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew war

notifications:
  email:
    recipients:
    - patel.shu@husky.neu.edu
    - sawant.ap@husky.neu.edu
    - chabhadia.r@husky.neu.edu

