language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew build

after_success:
 - mkdir codedeploy
 - zip -r csye6225.zip build/libs/ROOT.war appspec.yml restart.sh
 - ls -al
 - mv csye6225.zip codedeploy/
 - ls -al
 - pwd
 - cd codedeploy
 - ls -al
 - pwd


before_deploy:
 - cd ..


deploy:
 - provider: s3
   access_key_id: $access_key_id
   secret_access_key: $secret_access_key
   local_dir: codedeploy
   bucket: $bucket
   region: us-east-1
   skip_cleanup: true
   on :
    all_branches: true
 - provider: codedeploy
   access_key_id: $access_key_id
   secret_access_key: $secret_access_key
   bucket: $bucket
   key: csye6225.zip
   bundle_type: zip
   application: SimpleTestJAVA
   deployment_group: CSYE6225
   region: us-east-1
   wait-until-deployed: true
   on :
    all_branches: true

notifications:
  email:
    recipients:

    - patel.shu@husky.neu.edu
    - sawant.ap@husky.neu.edu
    - chabhadia.r@husky.neu.edu
