version: 0.0
os: linux

files:
  - source: ./appspec.yml
    destination: /home/ubuntu
  - source: ./restart.sh
    destination: /home/ubuntu
  - source: ./build/libs/ROOT.war
    destination: /var/lib/tomcat8/webapps

