version: 0.0

os: linux




files:
  - source: ./appspec.yml
    destination: /home/ubuntu
  - source: ./Infrastructure/aws/cloudwatch/awslog.conf
    destination: /home/ubuntu
  - source: ./restart.sh
    destination: /home/ubuntu
  - source: ./restartCloudWatch.sh
    destination: /home/ubuntu
  - source: ./build/libs/ROOT.war
    destination: /var/lib/tomcat8/webapps

hooks:
  AfterInstall:
  - location: ./restartTomcat.sh
    timeout: 180
    runas: ubuntu
  - location: ./restartCloudWatch.sh
    timeout: 180
    runas: ubuntu